### ISSUE TITLE
Product Query added dataframes to the ['data'] key?

### ISSUE THREAD

**Issue by dehidehidehi** [akaszynski/keepa#79]
Keepa wrapper 1.1.0 :

It seems making a product query added dataframes in the ['data'] key of the dictionnary.
Is this intentional? I don't see a mention of this anywhere,
screenshot below

Cheers,

[https://i.imgur.com/4n7cCdd.png](https://i.imgur.com/4n7cCdd.png)

**Comment by akaszynski** [comment]
That was added in #71, but there's no documentation for this at the moment.

Currently, this module isn't directly supported (financially or otherwise) by keepa and it's becoming increasingly hard to find time to maintain it.  If you'd like to contribute some additional documentation for this feature, please feel free to submit a PR.  Otherwise, it might take some time for me to get around to updating the module.

**Comment by kevincojean** [comment]
Thank you, I'll try my best to help maintain it, you've done a great job
